name: peaku
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'
dependencies:

  sqflite: ^2.3.0
  path: ^1.8.0
  
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_keyboard_visibility: ^6.0.0
  #flutter_survey: ^0.1.4
  survey_kit: ^0.2.0
  quick_quiz_view: ^0.0.2
  material_color_generator: ^1.1.0
  audioplayers: ^6.0.0

dev_dependencies:

  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true
  fonts:
    - family: Barlow
      fonts:
        - asset: assets/fonts/Barlow/Barlow-ExtraBold.ttf
          weight: 700
        - asset: assets/fonts/Barlow/Barlow-LightItalic.ttf
          style: italic
        - asset: assets/fonts/Barlow/Barlow-Light.ttf
        
        

  assets:
    - assets/images/PapelTransparent.png
    - assets/images/background.png
    - assets/images/logo.png
    - assets/images/logoimg.png
    - assets/images/logotxt.png
    - assets/images/Arrow.png
    - assets/textFiles/responses.txt
    - assets/mindfulness.m4a