import 'package:flutter_survey/flutter_survey.dart';
import 'package:flutter/material.dart';
List<QuestionResult> lastSurveyResults = [];
String pass = '';
String email = '';
bool enabled = true;
bool responded = false;
String userResponse = '';
String selectedQuestion = 'Loading...';
String holderText = 'Lorem Ispum fake response';
Color blue = const Color.fromARGB(255, 15, 49, 86);
Color orange = const Color.fromARGB(255, 232, 105, 0);
//MaterialColor material = MaterialColorGenerator.from(blue);
TextEditingController responseController = TextEditingController(text: userResponse);